
-- Roles
create type public.user_role as enum ('admin','venue','artist');

-- Booking request status
do $$ begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
                 where n.nspname = 'public' and t.typname = 'booking_request_status') then
    create type public.booking_request_status as enum (
      'pending','reviewing','sent_to_artists','proposal_sent','client_review',
      'client_approved','client_declined','confirmed','cancelled','archived'
    );
  end if;
end $$;

-- Proposal status
do $$ begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
                 where n.nspname = 'public' and t.typname = 'proposal_status') then
    create type public.proposal_status as enum ('sent','accepted','rejected','needs_changes');
  end if;
end $$;

-- Request artist status
do $$ begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
                 where n.nspname = 'public' and t.typname = 'request_artist_status') then
    create type public.request_artist_status as enum ('invited','accepted','declined');
  end if;
end $$;

-- Profiles mirror auth.users
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role user_role not null default 'venue',
  full_name text,
  avatar_url text,
  phone text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.venues (
  id uuid primary key references auth.users(id) on delete cascade,
  company_name text not null,
  vat_number text,
  address text,
  address_line1 text,
  postal_code text,
  city text,
  country text,
  contact_name text,
  contact_email text,
  billing_email text,
  contact_phone text,
  subscription_plan public.subscription_plan not null default 'free',
  is_pro boolean not null default false,
  plan_started_at timestamptz,
  plan_expires_at timestamptz,
  created_at timestamp with time zone default now()
);

create table if not exists public.artists (
  id uuid primary key references auth.users(id) on delete cascade,
  stage_name text not null,
  bio text,
  genres text[],
  formations text[],
  tech_needs text,
  min_fee numeric(12,2),
  travel_from text,
  portfolio_url text,
  instagram_url text,
  youtube_url text,
  facebook_url text,
  tiktok_url text,
  instagram_media_url text,
  contact_phone text,
  is_active boolean not null default true,
  created_at timestamp with time zone default now()
);

create table if not exists public.event_formats (
  id int generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  base_fee numeric(12,2),
  duration_minutes int,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

create table if not exists public.booking_requests (
  id uuid default gen_random_uuid() primary key,
  venue_id uuid references auth.users(id) on delete set null,
  event_format_id int references public.event_formats(id),
  event_format text,
  title text,
  event_date date,
  location text,
  audience_size int,
  notes text,
  formation text,
  start_time text,
  duration_minutes int,
  venue_company_name text,
  venue_address text,
  venue_contact_name text,
  venue_contact_phone text,
  venue_contact_email text,
  practical_info text,
  commission_rate numeric(6,4) default 0,
  status booking_request_status not null default 'pending',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint booking_requests_event_format_chk
    check (event_format is null or event_format ~ '^[a-z0-9]+([_-][a-z0-9]+)*$')
);

create table if not exists public.request_artists (
  id bigserial primary key,
  request_id uuid references public.booking_requests(id) on delete cascade,
  artist_id uuid references auth.users(id) on delete cascade,
  invited_by uuid references auth.users(id),
  status request_artist_status not null default 'invited',
  response_message text,
  responded_at timestamptz,
  created_at timestamp with time zone default now(),
  unique(request_id, artist_id)
);

create table if not exists public.availability_responses (
  id bigserial primary key,
  request_id uuid references public.booking_requests(id) on delete cascade,
  artist_id uuid references auth.users(id) on delete cascade,
  available boolean,
  message text,
  created_at timestamp with time zone default now(),
  unique(request_id, artist_id)
);

create table if not exists public.proposals (
  id uuid default gen_random_uuid() primary key,
  request_id uuid references public.booking_requests(id) on delete cascade,
  artist_id uuid references auth.users(id) on delete set null,
  fee numeric(12,2),
  tech_rider text,
  hospitality_rider text,
  notes text,
  client_note text,
  status proposal_status not null default 'sent',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.itineraries (
  id uuid default gen_random_uuid() primary key,
  proposal_id uuid references public.proposals(id) on delete cascade,
  request_id uuid references public.booking_requests(id) on delete cascade,
  target text,
  title text,
  data_json jsonb default '{}'::jsonb,
  call_time timestamptz,
  soundcheck_time timestamptz,
  show_time timestamptz,
  contact_on_site text,
  logistics text,
  created_at timestamp with time zone default now()
);

create table if not exists public.feedbacks (
  id bigserial primary key,
  request_id uuid references public.booking_requests(id) on delete cascade,
  from_role user_role not null,
  rating int check (rating between 1 and 5),
  comment text,
  created_at timestamp with time zone default now()
);

create table if not exists public.invoices (
  id uuid default gen_random_uuid() primary key,
  proposal_id uuid references public.proposals(id) on delete set null,
  artist_id uuid references auth.users(id) on delete set null,
  venue_id uuid references auth.users(id) on delete set null,
  amount numeric(12,2),
  status text not null default 'draft', -- draft, sent, paid, void
  billing_info jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.notifications (
  id bigserial primary key,
  user_id uuid references auth.users(id) on delete cascade,
  type text,
  payload jsonb,
  read_at timestamptz,
  created_at timestamp with time zone default now()
);

create table if not exists public.request_pricing (
  id bigserial primary key,
  request_id uuid references public.booking_requests(id) on delete cascade unique,
  client_quote numeric(12,2),
  artist_fee numeric(12,2),
  internal_costs numeric(12,2),
  currency text default 'EUR',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- Subscription plans (incl. free)
do $$ begin
  if not exists (select 1 from pg_type typ join pg_namespace nsp on nsp.oid = typ.typnamespace
                 where nsp.nspname = 'public' and typ.typname = 'subscription_plan') then
    create type public.subscription_plan as enum ('free','starter','pro','premium');
  end if;
end $$;

do $$ begin
  if exists (select 1 from pg_type typ join pg_namespace nsp on nsp.oid = typ.typnamespace
             where nsp.nspname = 'public' and typ.typname = 'subscription_plan')
     and not exists (select 1 from pg_enum e join pg_type t on t.oid = e.enumtypid
                     where t.typname = 'subscription_plan' and enumlabel = 'free') then
    alter type public.subscription_plan add value if not exists 'free';
  end if;
end $$;

alter table if exists public.venues
  alter column subscription_plan set default 'free';

-- Payment modes for booking requests
do $$ begin
  if not exists (select 1 from pg_type typ join pg_namespace nsp on nsp.oid = typ.typnamespace
                 where nsp.nspname = 'public' and typ.typname = 'payment_mode') then
    create type public.payment_mode as enum ('artist_invoice','guso','asso_un_dimanche','other');
  end if;
end $$;

alter table if exists public.booking_requests
  add column if not exists payment_mode public.payment_mode default 'other';

-- Unlocked artists per venue
create table if not exists public.venue_unlocked_artists (
  id bigserial primary key,
  venue_id uuid references auth.users(id) on delete cascade,
  artist_id uuid references auth.users(id) on delete cascade,
  first_unlocked_at timestamp with time zone default now(),
  unlocked_by_proposal_id uuid references public.proposals(id) on delete set null,
  constraint venue_unlocked_artists_unique unique (venue_id, artist_id)
);

create index if not exists venue_unlocked_artists_venue_idx on public.venue_unlocked_artists(venue_id);
create index if not exists venue_unlocked_artists_artist_idx on public.venue_unlocked_artists(artist_id);
